print('\n Input statement in python3')
print('-------------------------------')
str1=input("Enter the String1:")
str2=input("Enter the String2:")
str3=input("Enter the String3:")
print("\nBefore converting the values")
print("---------------------------------")
print('\nAddition of two values : ',str1+str2)
print("\nAfter Converting the values")
print("---------------------------------")
print('Addition of two values :',int(str1)+int(str2))
print('The Value of str3 is:',str3)
