from Tkinter import *
import ttk
import pymysql
def insert():
    dbconnect=pymysql.connect("localhost","root",
"ebs123","gui")
    cur=dbconnect.cursor()
    rno=int(tb1.get())
    name=tb2.get()
    cur.execute("insert into sample(rollno,name) values('%d','%s')"%(rno,name))
    dbconnect.commit()
    dbconnect.close()
root=Tk()
root.title("GuiEnvironment")
root.geometry("600x600")
app=Frame(root)
app.grid()
tlabel=Label(root,text="Data base connection")
tlabel.grid(row=1,column=15)
tlabel1=Label(root,text="---------------------------------")
tlabel1.grid(row=2,column=15)
label1=Label(root,text="Rollno")
label1.grid(row=6,column=0)
tb1=Entry(root)
tb1.grid(row=6,column=10)
label2=Label(root,text="Name")
label2.grid(row=6,column=11)
tb2=Entry(root)
tb2.grid(row=6,column=13)
button2=Button(root,text="submit",command=insert)
button2.grid(row=7,column=10)
button1=Button(root,text="End",command=root.destroy)
button1.grid(row=7,column=13)
root.mainloop()
